modLoader="javafml"
loaderVersion="[36,)"
license="ARR"
issueTrackerURL="https://github.com/ThDilos/ThDilos.Fox.Origin/issues"
description='''
ThDilos' Custom Made Fox Origins Expanded. Moderately overpowered.
'''

[[mods]]
modId="thorigins2"
version="3.1.0"
displayName="ThDilos Fox Origins Expanded"

[[dependencies.thorigins2]]
modId="thorigins"
mandatory=true
versionRange="[4.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins2]]
modId="origins"
mandatory=true
versionRange="[1.9.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins2]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20.4]"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins2]]
modId="pehkui"
mandatory=true
versionRange="[3.6.0,)"
ordering="NONE"
side="BOTH"