modLoader="javafml"
loaderVersion="[36,)"
license="ARR"
issueTrackerURL="https://github.com/ThDilos/ThDilos.Fox.Origin/issues"
description='''
Added a few evolutions for the base fox.
'''

[[mods]]
modId="thorigins2"
version="3.5.0"
displayName="ThDilos Fox Origins Expanded"

[[dependencies.thorigins2]]
modId="thorigins"
mandatory=true
versionRange="[4.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins]]
modId="origins"
mandatory=true
versionRange="[1.12.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins]]
modId="pehkui"
mandatory=true
versionRange="[3.3.3,)"
ordering="NONE"
side="BOTH"