modLoader="javafml"
loaderVersion="[36,)"
license="ARR"
issueTrackerURL="https://github.com/ThDilos/ThDilos.Fox.Origin/issues"
description='''
Fox Evolutions for ThDilos Fox Origin.
'''

[[mods]]
modId="thorigins2"
version="3.4.0"
displayName="ThDilos Fox Origins Expanded"

[[dependencies.thorigins2]]
modId="thorigins"
mandatory=true
versionRange="[4.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins2]]
modId="origins"
mandatory=true
versionRange="[1.6.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins2]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.19.3]"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins2]]
modId="pehkui"
mandatory=true
versionRange="[3.6.0,)"
ordering="NONE"
side="BOTH"